package com.example.infotainment_trip.model

data class TripDataItem(
    val DriverName: String,
    val EndDate: String,
    val EndLocation: String,
    val EndOdometer: String,
    val StartDate: String,
    val StartLocation: String,
    val StartOdometer: String,
    val TripStatus: String,
    val avgEngineSpeed: String,
    val avgSpeed: String,
    val cumDistance: String,
    val cumIdleMins: String,
    val cumMovTime: String,
    val cumStopMins: String,
    val driverScore: String,
    val fuelConsumedMaf: String,
    val harshAccCount: Int,
    val harshBrakeCount: Int,
    val last30mile: Double,
    val maxEngineSpeed: String,
    val maxSpeed: String,
    val mileageMaf: String,
    val strEndDate: String,
    val strStartDate: String,
    val totDistance: String,
    val totaldriverscore: Double,
    val trailData: List<String>,
    val tripDuration: String,
    val vehicleNo: String,
    var startAddress:String = "",
    var endAddress:String = ""
)