package com.example.infotainment_trip.model

data class TripDataItem(
    val DriverName: String? = "",
    val EndDate: String? = "",
    val EndLocation: String? = "",
    val EndOdometer: String? = "",
    val HAAlertCount: Int? = 0,
    val HBAlertCount: Int? = 0,
    val HCAlertCount: Int?= 0,
    val StartDate: String?= "",
    val StartLocation: String?= "",
    val StartOdometer: String?= "",
    val TripStatus: String?= "",
    val alertList: List<Alert>?,
    val avgEngineSpeed: String?= "",
    val avgSpeed: String?= "",
    val avgSpeedMiles: String?= "",
    val cumDistance: String?= "",
    val cumDistanceMiles: String?= "",
    val cumIdleMins: String?= "",
    val cumMovTime: String?= "",
    val cumStopMins: String?= "",
    val idleAlertCount: Int?= 0,
    val maxEngineSpeed: String?= "",
    val maxSpeed: String?= "",
    val maxSpeedMiles: String?= "",
    val speedAlertCount: Int?= 0,
    val strEndDate: String?= "",
    val strStartDate: String?= "",
    val totDistance: String?= "",
    val totDistanceMiles: String?= "",
    val tripDuration: String?= "",
    val tripFuelConsumption: String?= "",
    val tripFuelDip: String?= "",
    val tripFuelRefill: String?= "",
    val tripMileage: String?= "",
    val tripMileageMiles: String?= "",
    var startAddress : String? = "",
    var endAddress : String? = ""
)