package com.example.infotainment_trip.model

data class TripDataItem(
    val DriverName: String,
    val EndDate: String,
    val EndLocation: String,
    val EndOdometer: String,
    val HAAlertCount: Int,
    val HBAlertCount: Int,
    val HCAlertCount: Int,
    val StartDate: String,
    val StartLocation: String,
    val StartOdometer: String,
    val TripStatus: String,
    val alertList: List<Alert>,
    val avgEngineSpeed: String,
    val avgSpeed: String,
    val avgSpeedMiles: String,
    val cumDistance: String,
    val cumDistanceMiles: String,
    val cumIdleMins: String,
    val cumMovTime: String,
    val cumStopMins: String,
    val idleAlertCount: Int,
    val maxEngineSpeed: String,
    val maxSpeed: String,
    val maxSpeedMiles: String,
    val speedAlertCount: Int,
    val strEndDate: String,
    val strStartDate: String,
    val totDistance: String,
    val totDistanceMiles: String,
    val tripDuration: String,
    val tripFuelConsumption: String,
    val tripFuelDip: String,
    val tripFuelRefill: String,
    val tripMileage: String,
    val tripMileageMiles: String,
    var startAddress : String = "",
    var endAddress : String = ""
)